### ISSUE TITLE
Move bamboo integration to its own gradle file

### ISSUE THREAD

**Issue by TheTemportalist** [dsirius/Gradle-repo#3]
References:
https://github.com/dsirius/Gradle-repo/blob/master/scripts/forge/builtbroken.gradle#L33-L38
https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/changelog.gradle#L6 (make this line configurable?)
https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/changelog.gradle#L34
https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/jars.gradle#L15
https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/maven.gradle#L14
https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/archive.gradle

**Comment by dmodoomsirius** [comment]
I think https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/jars.gradle#L15-L16 can be removed.

change https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/archive.gradle#L1 to match https://github.com/dsirius/Gradle-repo/blob/master/scripts/both/jars.gradle#L58
